# Generated by Django 4.0.1 on 2022-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customer_email_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('MALE', 'famale')], max_length=10, null=True),
        ),
    ]
